# Generated by Django 3.0.4 on 2020-04-20 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('o_date', models.DateField(verbose_name='date published')),
                ('price', models.FloatField(max_length=10)),
                ('quantity', models.IntegerField(default=1)),
                ('images', models.CharField(default='', max_length=30)),
                ('item', models.CharField(default='', max_length=20)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product')),
            ],
        ),
    ]
