# Generated by Django 3.0.4 on 2020-04-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_userorders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrders',
        ),
    ]
