# Generated by Django 3.0.4 on 2020-03-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('mobile_no', models.BigIntegerField()),
                ('address', models.CharField(default='', max_length=200)),
                ('cimg', models.ImageField(default='static/default/a.JPEG', upload_to='login/images')),
            ],
        ),
    ]
