# Generated by Django 3.0.4 on 2020-03-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20200318_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cimg',
            field=models.ImageField(default='static/default/a.JPEG', upload_to='login/images'),
        ),
    ]
