# Generated by Django 3.0.4 on 2020-03-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(default=None, max_length=20)),
                ('product_name', models.CharField(default=None, max_length=100)),
                ('catagory', models.CharField(default=None, max_length=50)),
                ('product_discription', models.CharField(max_length=900)),
                ('price', models.FloatField(default=0.0)),
                ('img', models.ImageField(default='static/default/a.JPEG', upload_to='eshop/images')),
            ],
        ),
    ]
